server:
  port: 8060

spring:
  application:
    name: zuul-api-gateway-service

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    db-service:
      path: /db-service/**
      service-id: db-service
    stock-service:
      path: /stock-service/**
      service-id: stock-service