server:
  port: 8060

spring:
  application:
    name: zuul-api-gateway-service

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    db-service:
      path: /db-service/**
      url: http://db-service
    stock-service:
      path: /stock-service/**
      url: http://stock-service